version: '3.8'

services:
  app:
    container_name: 'life_disk_app_container'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
  db:
    image: 'mysql'
    container_name: 'life_disk_db_container'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: life_disk